# This config file is managed by the `crackle config` sub-command.
# NOT ADVISED TO HAND EDIT

# Default config locations:
#   Mac: $HOME/.cr/client.toml
#   Linux: $XDG_CONFIG_HOME/.cr/client.toml, $HOME/.cr/client.toml
#   Windows: Hahaha

[crackle]
api = "https://api.crackle.pm/api/"

[crackle.auth]
username = "example"
apikey = "apikey"
